Post
Society-Project/Society pull request #13
Opened 2023-02-09 21:53 UTC by SCholakov05

[Create post and post design](https://trello.com/c/f9iOiy2b/9-main-page-posts)

2023-02-09 21:57 UTC, petya0111 reviewed
Good job

2023-02-09 21:57 UTC, petya0111 commented on client/src/app/layout.tsx
> +  background-color: #ebebeb;
This can be global variable

2023-02-10 13:14 UTC, IvayloSlavchev requested changes

2023-02-10 13:14 UTC, IvayloSlavchev commented on client/src/components/posts/postReactions/Comments/CommentInput.tsx
> +                        onChange={(e) => setText(e.target.value)}
Try to avoid single character variable names.

2023-02-10 13:14 UTC, IvayloSlavchev commented on client/src/components/posts/postReactions/Comments/CmntFuncionality.tsx
> +                                                                            onChange={(e) =>
Avoid signle character variables.

2023-02-10 13:14 UTC, IvayloSlavchev commented on client/src/components/posts/postReactions/Comments/CmntFuncionality.tsx
> +                                                            <Avatar sx={{ marginLeft: 2, backgroundColor: 'green' }}>R</Avatar>
Can you remove the R and use self closing tag instead?

2023-02-10 13:14 UTC, IvayloSlavchev commented on client/src/components/posts/postReactions/Comments/CmntFuncionality.tsx
> +                                                                    onChange={(e) =>
Please try to use more expensive variable names such as:  "event". It is more understandable and also you  avoid signle character variables.

2023-02-10 13:14 UTC, IvayloSlavchev commented on client/src/components/posts/postReactions/Comments/CmntFuncionality.tsx
> +                                                                                c.id === comment.id ? { ...c, text: e.target.value } : c
Same here.

2023-02-10 13:14 UTC, IvayloSlavchev commented on client/src/components/posts/postReactions/Comments/CmntFuncionality.tsx
> +                                                                                        c.id === comment.id ? { ...c, text: e.target.value } : c
Same here.

2023-02-10 13:14 UTC, IvayloSlavchev commented on client/src/components/posts/postReactions/Comments/CommentInput.tsx
> +    const onSubmitHandler = (e: React.FormEvent<HTMLButtonElement>) => {
Avoid signle character variable names.

2023-02-10 19:53 UTC, IvayloSlavchev approved these changes
LGTM!

2023-02-10 19:53 UTC, petya0111 approved these changes
Great work and perfect implementation of design ✓

2023-02-10 19:55 UTC, merged