Created Dockerfile | Added .gitignore file to server directory
Society-Project/Society pull request #6
Opened 2023-01-22 14:00 UTC by IvayloSlavchev

2023-01-22 14:02 UTC, petya0111 approved these changes, later dismissed
Looks good.

2023-01-22 14:05 UTC, petya0111 reviewed
Test it again.

2023-01-23 10:17 UTC, petya0111 reviewed
Did you test some of your endpoints to approve that all is working on the docker container?

2023-01-27 16:23 UTC, petya0111 requested changes
Some comments about API endpoint better naming conventions.

2023-01-27 16:23 UTC, petya0111 commented on server/auth/authorization.js
> +app.post('/renewAccessToken', (req, res) => {
Please make endpoints with dashes or in a path style. 
And read specifications on how to make better endpoint naming.
https://blog.dreamfactory.com/best-practices-for-naming-rest-api-endpoints/

2023-01-27 16:23 UTC, petya0111 commented on server/auth/authorization.js
> +    jwt.verify(refreshToken, process.env.REFRESH_TOKEN_ACCESS, (err, user) => {
Please do not use camel case in the endpoint naming.

2023-01-27 16:23 UTC, petya0111 commented on server/auth/authorization.js
> +    let refreshToken = jwt.sign(user, process.env.REFRESH_TOKEN_ACCESS, { expiresIn: "7d" });
I think the refresh token should have for example '1h' one hour, but not 7 days..

2023-01-28 09:05 UTC, petya0111 requested changes
Please use DTO objects to have known types in Typescript.

2023-01-28 09:05 UTC, petya0111 commented on server/auth/authorization.ts
> +function auth(req: any, res: any, next: any){
The request/response body can be made with a DTO object to have a more clear type of object, Typescript helps very well with that. 
Please use strictly the object and needed fields that should be used. 
`any` type is a very unknown thing and you should write clear types. Thank you :)

2023-01-29 14:33 UTC, TeoLucidWork commented
@IvayloSlavchev , there are not unit tests here.

2023-01-30 17:48 UTC, petya0111 approved these changes
Great work @IvayloSlavchev

2023-01-30 17:53 UTC, merged